### ISSUE TITLE
scaner doesn't properly read artefacts

### ISSUE THREAD

**Issue by Veicy01** [Andrewthe13th/Inventory_Kamera#154]
after reading an artefact it displays an error "Unable to validate information for artifact #[number]"

**Comment by marcos49** [comment]
can confirm same thing happening to me

**Comment by Malkovitz** [comment]
same here

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If you no longer get the same error, please let us know so we can close this issue. 

If you get the same error, there will screenshots saved in the `logging` folder. Please upload a few of those to this issue so we can diagnose the problem better. Thanks!

**Comment by LinhMD** [comment]
I still having this issue v1.2

Here are the log:

Unable to validate information for artifact ID#87


Invalid artifact rarity

Artifact ID: 87

Set: WanderersTroupe

Rarity: 0

Level: 20

Slot: flower

Main Stat: hp

Substat 1: critRate_ + 7%

Substat 2: atk + 33

Substat 3: critDMG_ + 12.4%

Substat 4: hp_ + 14%

Locked: False

Equipped character: Venti

**Comment by Cupcak3** [comment]
This is an old issue and the original author hasn't replied in a little over three weeks so I am. 

If you are still having similar problems then please consider trying out the new v1.2.1-prerelease or opening a new issue. Be sure to include screenshots that the app generates for this error.
