### ISSUE TITLE
Error while scanning characters

### ISSUE THREAD

**Issue by SupremeVoid** [Andrewthe13th/Inventory_Kamera#7]
I changed the display mode to 1280x720 windowed and the scanning worked fine for weapons and artifacts.
When scanning the characters, it works for a few but then randomly opens the details page and gets stucked resulting in an error.
It happen on any random character in random order.

With 0.8 weapons and artifacts are not counted correct anymore?

**Comment by Andrewthe13th** [comment]
in 0.8 weapons and artifacts scanned show the 5-4 artifacts scanned and 5-3 star weapons scanned. artifacts 3-1 stars are discarded and are not shown in the count. same for weapons 2-1 stars. Not sure how the character scanner would get stuck in the details page, but i will look into it. Thanks for reporting.

**Comment by southrop** [comment]
I just tried v0.8 and it got stuck on scanning characters too. In my case, it stopped after the first character, who was Ayaka.

I'm not sure how exactly the character scanner works, but does it by any chance try to press the arrow on the ride side of the screen to go to the next character? If so, I observed the scanner open the details of a talent before it got stuck, gave up and went back to the Paimon menu, so perhaps it's clicking the wrong location now?

![image](https://user-images.githubusercontent.com/2568167/135734110-33c6f5c6-ae3a-4a0f-85f4-2e4c4bc23316.png)

**Comment by Andrewthe13th** [comment]
I believe the issue was timing but i definitely check it out. Its weird because it scans all the characters most of the time and will never stop on any chacater past the first one. I will make not be able to exit if more than one character has been scanned.

**Comment by thematica** [comment]
i have this issue too
only 1 character get scanned and thats Raiden my current on-screen char

also, thank you for this tool

**Comment by PTracana** [comment]
Same problem here. made an issue earlier but decided to close it since it's the same
will try running it a couple more times since thematica got it to work that way

**Comment by nikinack** [comment]
> i have this issue too only 1 character get scanned and thats Raiden my current on-screen char
> 
> also, thank you for this tool
> 
> edit: run it the 3rd time, the works. all char scanned. i don't know why though

I was also having the same issue, with the same solution. Third times the charm I guess.

**Comment by Andrewthe13th** [comment]
Strange I thought i fixed it. I guess i have to take another look at it.

**Comment by PTracana** [comment]
this happened in update v0.8 doesn't seem to be happening now

**Comment by thelostabbey** [comment]
I am still facing this/similar issue in 0.9, it will scan weapons/artifacts ok (some duplicates) but crashes on characters.  I feel the scanner may be going to fast for my pc so maybe we can add a second delay between each scan?

**Comment by Cupcak3** [comment]
Andrew seems to have fixed this issue and it is included in the [v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease) so I am closing this issue. Please reopen this issue if the problem persists.
